/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2019-12-31 12:24:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.developer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class appinfoadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/jsp/developer/common/js.jsp", Long.valueOf(1502955762073L));
    _jspx_dependants.put("file:/C:/Users/Hasee/.m2/repository/org/glassfish/web/jstl-impl/1.2/jstl-impl-1.2.jar", Long.valueOf(1577511543994L));
    _jspx_dependants.put("/WEB-INF/jsp/developer/common/header.jsp", Long.valueOf(1502955762070L));
    _jspx_dependants.put("/WEB-INF/jsp/developer/common/footer.jsp", Long.valueOf(1502955762067L));
    _jspx_dependants.put("jar:file:/C:/Users/Hasee/.m2/repository/org/glassfish/web/jstl-impl/1.2/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308098170000L));
    _jspx_dependants.put("jar:file:/C:/Users/Hasee/.m2/repository/org/glassfish/web/jstl-impl/1.2/jstl-impl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1308098170000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<!-- Meta, title, CSS, favicons, etc. -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<title>APP开发者平台</title>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- Font Awesome -->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- NProgress -->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/nprogress.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- iCheck -->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/green.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- bootstrap-progressbar -->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/bootstrap-progressbar-3.3.4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- JQVMap -->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/jqvmap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/dropzone.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- Custom Theme Style -->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/css/custom.min.css\"\trel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- add localcss 2016-8-18 -->\r\n");
      out.write("\t<link href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/localcss/appinfoadd.css' rel='stylesheet'>\r\n");
      out.write("\t<link href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/localcss/appinfolist.css' rel='stylesheet'>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"nav-md footer_fixed\">\r\n");
      out.write("\t<div class=\"container body\">\r\n");
      out.write("\t\t<div class=\"main_container\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3 left_col menu_fixed\">\r\n");
      out.write("\t\t\t\t<div class=\"left_col scroll-view\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar nav_title\" style=\"border: 0;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/flatform/main\" class=\"site_title\"><i class=\"fa fa-paw\"></i> <span>APP\r\n");
      out.write("\t\t\t\t\t\t\t\tBMS</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- menu profile quick info -->\r\n");
      out.write("\t\t\t\t\t<div class=\"profile\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"profile_pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/images/img.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"...\" class=\"img-circle profile_img\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"profile_info\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>Welcome,</span>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${devUserSession.devCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /menu profile quick info -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- sidebar menu -->\r\n");
      out.write("\t\t\t\t\t<div id=\"sidebar-menu\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"main_menu_side hidden-print main_menu\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"menu_section\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${devUserSession.devName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav side-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a><i class=\"fa fa-home\"></i> APP账户管理 <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-chevron-down\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nav child_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:;\">APP开发者账户申请</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:;\">个人账户信息维护</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a><i class=\"fa fa-edit\"></i> APP应用管理<span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-chevron-down\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nav child_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/flatform/app/list\">APP维护</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /sidebar menu -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- /menu footer buttons -->\r\n");
      out.write("\t\t\t\t\t<div class=\"sidebar-footer hidden-small\">\r\n");
      out.write("\t\t\t\t\t\t<a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Settings\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t</a> <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"FullScreen\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-fullscreen\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t</a> <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Lock\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-eye-close\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t\t\t</a> <a data-toggle=\"tooltip\" data-placement=\"top\" title=\"Logout\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/logout\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-off\" aria-hidden=\"true\"></span> </a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /menu footer buttons -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- top navigation -->\r\n");
      out.write("\t\t\t<div class=\"top_nav\">\r\n");
      out.write("\t\t\t\t<div class=\"nav_menu\">\r\n");
      out.write("\t\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nav toggle\">\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"menu_toggle\"><i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a href=\"javascript:;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"user-profile dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-expanded=\"false\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/images/img.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${devUserSession.devCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\" fa fa-angle-down\"></span> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-usermenu pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dev/logout\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-sign-out pull-right\"></i> Log Out</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"presentation\" class=\"dropdown\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"menu1\" class=\"dropdown-menu list-unstyled msg_list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trole=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a> <span class=\"image\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/images/img.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"Profile Image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span> <span>John Smith</span> <span class=\"time\">3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmins ago</span> </span> <span class=\"message\"> Film festivals used\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tto be do-or-die moments for movie makers. They were where...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a> <span class=\"image\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/images/img.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"Profile Image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span> <span>John Smith</span> <span class=\"time\">3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmins ago</span> </span> <span class=\"message\"> Film festivals used\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tto be do-or-die moments for movie makers. They were where...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a> <span class=\"image\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/images/img.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"Profile Image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span> <span>John Smith</span> <span class=\"time\">3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmins ago</span> </span> <span class=\"message\"> Film festivals used\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tto be do-or-die moments for movie makers. They were where...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a> <span class=\"image\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/images/img.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"Profile Image\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> <span> <span>John Smith</span> <span class=\"time\">3\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmins ago</span> </span> <span class=\"message\"> Film festivals used\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tto be do-or-die moments for movie makers. They were where...\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span> </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a> <strong>See All Alerts</strong> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-right\"></i> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /top navigation -->\r\n");
      out.write("\t\t\t<div class=\"right_col\" role=\"main\">\r\n");
      out.write("\t\t\t\t<div class=\"\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("    <div class=\"x_panel\">\r\n");
      out.write("      <div class=\"x_title\">\r\n");
      out.write("        <h2>新增APP基础信息 <i class=\"fa fa-user\"></i><small>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${devUserSession.devName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</small></h2>\r\n");
      out.write("             <div class=\"clearfix\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"x_content\">\r\n");
      out.write("\t  <!-- <div class=\"item form-group\">\r\n");
      out.write("               <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" ></label>\r\n");
      out.write("               <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("                 <form action=\"uploadlogo\" class=\"dropzone\" style=\"height:100px;\">\r\n");
      out.write("                 </form>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div> -->\r\n");
      out.write("           <div class=\"clearfix\"></div>\r\n");
      out.write("        <form class=\"form-horizontal form-label-left\" action=\"appinfoaddsave\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"name\">软件名称 <span class=\"required\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <input id=\"softwareName\" class=\"form-control col-md-7 col-xs-12\" \r\n");
      out.write("               data-validate-length-range=\"20\" data-validate-words=\"1\" name=\"softwareName\"  required=\"required\"\r\n");
      out.write("               placeholder=\"请输入软件名称\" type=\"text\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"name\">APK名称 <span class=\"required\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <input id=\"APKName\" class=\"form-control col-md-7 col-xs-12\" \r\n");
      out.write("              \tdata-validate-length-range=\"20\" data-validate-words=\"1\" name=\"APKName\"   required=\"required\"\r\n");
      out.write("              \tplaceholder=\"请输入APK名称\" type=\"text\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"name\">支持ROM <span class=\"required\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <input id=\"supportROM\" class=\"form-control col-md-7 col-xs-12\" name=\"supportROM\" \r\n");
      out.write("              \tdata-validate-length-range=\"20\" data-validate-words=\"1\"   required=\"required\"\r\n");
      out.write("              \tplaceholder=\"请输入支持的ROM\" type=\"text\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"name\">界面语言 <span class=\"required\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <input id=\"interfaceLanguage\" class=\"form-control col-md-7 col-xs-12\" \r\n");
      out.write("              data-validate-length-range=\"20\" data-validate-words=\"1\" name=\"interfaceLanguage\"   required=\"required\"\r\n");
      out.write("              placeholder=\"请输入软件支持的界面语言\" type=\"text\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"number\">软件大小 <span class=\"required\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <input type=\"number\" id=\"softwareSize\" name=\"softwareSize\"   required=\"required\" onkeyup=\"value=value.replace(/[^\\d]/g,'')\"\r\n");
      out.write("              data-validate-minmax=\"10,500\"  placeholder=\"请输入软件大小，单位为Mb\" class=\"form-control col-md-7 col-xs-12\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"number\">下载次数 <span class=\"required\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <input type=\"number\" id=\"downloads\" name=\"downloads\"   required=\"required\"\r\n");
      out.write("              data-validate-minmax=\"10,500\"  placeholder=\"请输入下载次数\" class=\"form-control col-md-7 col-xs-12\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\"  for=\"select\">所属平台 <span class=\"required\">*</span></label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <select name=\"flatformId\" id=\"flatformId\" class=\"form-control\"   required=\"required\"></select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"select\">一级分类 <span class=\"required\">*</span></label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <select name=\"categoryLevel1\" id=\"categoryLevel1\" class=\"form-control\"   required=\"required\"> </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\"  for=\"select\">二级分类 <span class=\"required\">*</span></label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <select name=\"categoryLevel2\" id=\"categoryLevel2\" class=\"form-control\"  required=\"required\"></select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"select\">三级分类 <span class=\"required\">*</span></label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <select name=\"categoryLevel3\" id=\"categoryLevel3\" class=\"form-control\"  required=\"required\"></select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"name\">APP状态 <span class=\"required\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("            \t<input type=\"hidden\" name=\"status\" id=\"status\" value=\"2\">待审核\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"textarea\">应用简介 <span class=\"required\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("              <textarea id=\"appInfo\" name=\"appInfo\"     required=\"required\"\r\n");
      out.write("              placeholder=\"请输入本软件的相关信息，本信息作为软件的详细信息进行软件的介绍。\" class=\"form-control col-md-7 col-xs-12\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("           <div class=\"item form-group\">\r\n");
      out.write("            <label class=\"control-label col-md-3 col-sm-3 col-xs-12\" for=\"name\">LOGO图片 <span class=\"required\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n");
      out.write("            <input type=\"file\" class=\"form-control col-md-7 col-xs-12\" name=\"a_logoPicPath\"  required=\"required\" id=\"a_logoPicPath\"/>\r\n");
      out.write("            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fileUploadError }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"ln_solid\"></div>\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("              <button id=\"send\" type=\"submit\" class=\"btn btn-success\">保存</button>\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-primary\" id=\"back\">返回</button>\r\n");
      out.write("              <br/><br/>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write(" </div>\r\n");
      out.write("<!-- /page content -->\r\n");
      out.write("<!-- footer content -->\r\n");
      out.write("<footer>\r\n");
      out.write("\t<div class=\"pull-right\">©2016 All Rights Reserved.</div>\r\n");
      out.write("\t<div class=\"clearfix\"></div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- /footer content -->\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("   <!-- jQuery -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/js/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- FastClick -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/js/fastclick.js\"></script>\r\n");
      out.write("    <!-- NProgress -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/js/nprogress.js\"></script>\r\n");
      out.write("    <!-- jQuery custom content scroller -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/js/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("    <!-- Custom Theme Scripts -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/js/custom.min.js\"></script>\r\n");
      out.write("    <!-- validator -->\r\n");
      out.write("\r\n");
      out.write("    <!-- dropzone -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/js/dropzone.js\"></script>  ");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/statics/localjs/appinfoadd.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
