package com.jhx.projectd.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class AppInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.softwareName
     *
     * @mbg.generated
     */
    private String softwarename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.softwareSize
     *
     * @mbg.generated
     */
    private BigDecimal softwaresize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.cateLevel1
     *
     * @mbg.generated
     */
    private Integer catelevel1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.cateLevel2
     *
     * @mbg.generated
     */
    private Integer catelevel2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.softwareDomain
     *
     * @mbg.generated
     */
    private String softwaredomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.devId
     *
     * @mbg.generated
     */
    private Integer devid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.logPicPath
     *
     * @mbg.generated
     */
    private String logpicpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.versionId
     *
     * @mbg.generated
     */
    private Integer versionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.download
     *
     * @mbg.generated
     */
    private Long download;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.supportRom
     *
     * @mbg.generated
     */
    private String supportrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.appInfo
     *
     * @mbg.generated
     */
    private String appinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.id
     *
     * @return the value of app_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.id
     *
     * @param id the value for app_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.softwareName
     *
     * @return the value of app_info.softwareName
     *
     * @mbg.generated
     */
    public String getSoftwarename() {
        return softwarename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.softwareName
     *
     * @param softwarename the value for app_info.softwareName
     *
     * @mbg.generated
     */
    public void setSoftwarename(String softwarename) {
        this.softwarename = softwarename == null ? null : softwarename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.softwareSize
     *
     * @return the value of app_info.softwareSize
     *
     * @mbg.generated
     */
    public BigDecimal getSoftwaresize() {
        return softwaresize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.softwareSize
     *
     * @param softwaresize the value for app_info.softwareSize
     *
     * @mbg.generated
     */
    public void setSoftwaresize(BigDecimal softwaresize) {
        this.softwaresize = softwaresize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.status
     *
     * @return the value of app_info.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.status
     *
     * @param status the value for app_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.cateLevel1
     *
     * @return the value of app_info.cateLevel1
     *
     * @mbg.generated
     */
    public Integer getCatelevel1() {
        return catelevel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.cateLevel1
     *
     * @param catelevel1 the value for app_info.cateLevel1
     *
     * @mbg.generated
     */
    public void setCatelevel1(Integer catelevel1) {
        this.catelevel1 = catelevel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.cateLevel2
     *
     * @return the value of app_info.cateLevel2
     *
     * @mbg.generated
     */
    public Integer getCatelevel2() {
        return catelevel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.cateLevel2
     *
     * @param catelevel2 the value for app_info.cateLevel2
     *
     * @mbg.generated
     */
    public void setCatelevel2(Integer catelevel2) {
        this.catelevel2 = catelevel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.softwareDomain
     *
     * @return the value of app_info.softwareDomain
     *
     * @mbg.generated
     */
    public String getSoftwaredomain() {
        return softwaredomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.softwareDomain
     *
     * @param softwaredomain the value for app_info.softwareDomain
     *
     * @mbg.generated
     */
    public void setSoftwaredomain(String softwaredomain) {
        this.softwaredomain = softwaredomain == null ? null : softwaredomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.devId
     *
     * @return the value of app_info.devId
     *
     * @mbg.generated
     */
    public Integer getDevid() {
        return devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.devId
     *
     * @param devid the value for app_info.devId
     *
     * @mbg.generated
     */
    public void setDevid(Integer devid) {
        this.devid = devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.logPicPath
     *
     * @return the value of app_info.logPicPath
     *
     * @mbg.generated
     */
    public String getLogpicpath() {
        return logpicpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.logPicPath
     *
     * @param logpicpath the value for app_info.logPicPath
     *
     * @mbg.generated
     */
    public void setLogpicpath(String logpicpath) {
        this.logpicpath = logpicpath == null ? null : logpicpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.versionId
     *
     * @return the value of app_info.versionId
     *
     * @mbg.generated
     */
    public Integer getVersionid() {
        return versionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.versionId
     *
     * @param versionid the value for app_info.versionId
     *
     * @mbg.generated
     */
    public void setVersionid(Integer versionid) {
        this.versionid = versionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.download
     *
     * @return the value of app_info.download
     *
     * @mbg.generated
     */
    public Long getDownload() {
        return download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.download
     *
     * @param download the value for app_info.download
     *
     * @mbg.generated
     */
    public void setDownload(Long download) {
        this.download = download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.supportRom
     *
     * @return the value of app_info.supportRom
     *
     * @mbg.generated
     */
    public String getSupportrom() {
        return supportrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.supportRom
     *
     * @param supportrom the value for app_info.supportRom
     *
     * @mbg.generated
     */
    public void setSupportrom(String supportrom) {
        this.supportrom = supportrom == null ? null : supportrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.create_time
     *
     * @return the value of app_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.create_time
     *
     * @param createTime the value for app_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.update_time
     *
     * @return the value of app_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.update_time
     *
     * @param updateTime the value for app_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.appInfo
     *
     * @return the value of app_info.appInfo
     *
     * @mbg.generated
     */
    public String getAppinfo() {
        return appinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.appInfo
     *
     * @param appinfo the value for app_info.appInfo
     *
     * @mbg.generated
     */
    public void setAppinfo(String appinfo) {
        this.appinfo = appinfo == null ? null : appinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", softwarename=").append(softwarename);
        sb.append(", softwaresize=").append(softwaresize);
        sb.append(", status=").append(status);
        sb.append(", catelevel1=").append(catelevel1);
        sb.append(", catelevel2=").append(catelevel2);
        sb.append(", softwaredomain=").append(softwaredomain);
        sb.append(", devid=").append(devid);
        sb.append(", logpicpath=").append(logpicpath);
        sb.append(", versionid=").append(versionid);
        sb.append(", download=").append(download);
        sb.append(", supportrom=").append(supportrom);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", appinfo=").append(appinfo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}