package com.jhx.projectd.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class AppVersion implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.appId
     *
     * @mbg.generated
     */
    private Integer appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.versionNo
     *
     * @mbg.generated
     */
    private String versionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.publishStatus
     *
     * @mbg.generated
     */
    private Integer publishStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.downloadLink
     *
     * @mbg.generated
     */
    private String downloadLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.versionSize
     *
     * @mbg.generated
     */
    private BigDecimal versionSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.uodate_time
     *
     * @mbg.generated
     */
    private Date uodate_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.apkLocPath
     *
     * @mbg.generated
     */
    private String apkLocPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.apkFileName
     *
     * @mbg.generated
     */
    private String apkFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.versionInfo
     *
     * @mbg.generated
     */
    private String versionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_version
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.id
     *
     * @return the value of app_version.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.id
     *
     * @param id the value for app_version.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.appId
     *
     * @return the value of app_version.appId
     *
     * @mbg.generated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.appId
     *
     * @param appId the value for app_version.appId
     *
     * @mbg.generated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.versionNo
     *
     * @return the value of app_version.versionNo
     *
     * @mbg.generated
     */
    public String getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.versionNo
     *
     * @param versionNo the value for app_version.versionNo
     *
     * @mbg.generated
     */
    public void setVersionNo(String versionNo) {
        this.versionNo = versionNo == null ? null : versionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.publishStatus
     *
     * @return the value of app_version.publishStatus
     *
     * @mbg.generated
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.publishStatus
     *
     * @param publishStatus the value for app_version.publishStatus
     *
     * @mbg.generated
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.downloadLink
     *
     * @return the value of app_version.downloadLink
     *
     * @mbg.generated
     */
    public String getDownloadLink() {
        return downloadLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.downloadLink
     *
     * @param downloadLink the value for app_version.downloadLink
     *
     * @mbg.generated
     */
    public void setDownloadLink(String downloadLink) {
        this.downloadLink = downloadLink == null ? null : downloadLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.versionSize
     *
     * @return the value of app_version.versionSize
     *
     * @mbg.generated
     */
    public BigDecimal getVersionSize() {
        return versionSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.versionSize
     *
     * @param versionSize the value for app_version.versionSize
     *
     * @mbg.generated
     */
    public void setVersionSize(BigDecimal versionSize) {
        this.versionSize = versionSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.create_time
     *
     * @return the value of app_version.create_time
     *
     * @mbg.generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.create_time
     *
     * @param create_time the value for app_version.create_time
     *
     * @mbg.generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.uodate_time
     *
     * @return the value of app_version.uodate_time
     *
     * @mbg.generated
     */
    public Date getUodate_time() {
        return uodate_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.uodate_time
     *
     * @param uodate_time the value for app_version.uodate_time
     *
     * @mbg.generated
     */
    public void setUodate_time(Date uodate_time) {
        this.uodate_time = uodate_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.apkLocPath
     *
     * @return the value of app_version.apkLocPath
     *
     * @mbg.generated
     */
    public String getApkLocPath() {
        return apkLocPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.apkLocPath
     *
     * @param apkLocPath the value for app_version.apkLocPath
     *
     * @mbg.generated
     */
    public void setApkLocPath(String apkLocPath) {
        this.apkLocPath = apkLocPath == null ? null : apkLocPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.apkFileName
     *
     * @return the value of app_version.apkFileName
     *
     * @mbg.generated
     */
    public String getApkFileName() {
        return apkFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.apkFileName
     *
     * @param apkFileName the value for app_version.apkFileName
     *
     * @mbg.generated
     */
    public void setApkFileName(String apkFileName) {
        this.apkFileName = apkFileName == null ? null : apkFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.versionInfo
     *
     * @return the value of app_version.versionInfo
     *
     * @mbg.generated
     */
    public String getVersionInfo() {
        return versionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.versionInfo
     *
     * @param versionInfo the value for app_version.versionInfo
     *
     * @mbg.generated
     */
    public void setVersionInfo(String versionInfo) {
        this.versionInfo = versionInfo == null ? null : versionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", versionNo=").append(versionNo);
        sb.append(", publishStatus=").append(publishStatus);
        sb.append(", downloadLink=").append(downloadLink);
        sb.append(", versionSize=").append(versionSize);
        sb.append(", create_time=").append(create_time);
        sb.append(", uodate_time=").append(uodate_time);
        sb.append(", apkLocPath=").append(apkLocPath);
        sb.append(", apkFileName=").append(apkFileName);
        sb.append(", versionInfo=").append(versionInfo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}