package com.jhx.projectd.entity;

import java.io.Serializable;

public class DevTmp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_tmp.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_tmp.dev_name
     *
     * @mbg.generated
     */
    private String dev_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_tmp.dev_password
     *
     * @mbg.generated
     */
    private String dev_password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_tmp.dev_email
     *
     * @mbg.generated
     */
    private String dev_email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_tmp.is_active
     *
     * @mbg.generated
     */
    private Integer is_active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dev_tmp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_tmp.id
     *
     * @return the value of dev_tmp.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_tmp.id
     *
     * @param id the value for dev_tmp.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_tmp.dev_name
     *
     * @return the value of dev_tmp.dev_name
     *
     * @mbg.generated
     */
    public String getDev_name() {
        return dev_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_tmp.dev_name
     *
     * @param dev_name the value for dev_tmp.dev_name
     *
     * @mbg.generated
     */
    public void setDev_name(String dev_name) {
        this.dev_name = dev_name == null ? null : dev_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_tmp.dev_password
     *
     * @return the value of dev_tmp.dev_password
     *
     * @mbg.generated
     */
    public String getDev_password() {
        return dev_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_tmp.dev_password
     *
     * @param dev_password the value for dev_tmp.dev_password
     *
     * @mbg.generated
     */
    public void setDev_password(String dev_password) {
        this.dev_password = dev_password == null ? null : dev_password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_tmp.dev_email
     *
     * @return the value of dev_tmp.dev_email
     *
     * @mbg.generated
     */
    public String getDev_email() {
        return dev_email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_tmp.dev_email
     *
     * @param dev_email the value for dev_tmp.dev_email
     *
     * @mbg.generated
     */
    public void setDev_email(String dev_email) {
        this.dev_email = dev_email == null ? null : dev_email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_tmp.is_active
     *
     * @return the value of dev_tmp.is_active
     *
     * @mbg.generated
     */
    public Integer getIs_active() {
        return is_active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_tmp.is_active
     *
     * @param is_active the value for dev_tmp.is_active
     *
     * @mbg.generated
     */
    public void setIs_active(Integer is_active) {
        this.is_active = is_active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_tmp
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dev_name=").append(dev_name);
        sb.append(", dev_password=").append(dev_password);
        sb.append(", dev_email=").append(dev_email);
        sb.append(", is_active=").append(is_active);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}