package com.jhx.projectd.mapper;

import com.jhx.projectd.entity.AppInfo;
import com.jhx.projectd.utils.AppListColumn;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbg.generated
     */
    int insert(AppInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbg.generated
     */
    AppInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbg.generated
     */
    List<AppInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppInfo record);
    List<AppListColumn> selectByParams(@Param("params") Object params);
    List<AppListColumn> selectByAPKName(@Param("name") String name);


}