package com.jhx.projectd.mapper;

import com.jhx.projectd.entity.DevUser;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface DevUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */
    int insert(DevUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */
    DevUser selectByPrimaryKey(Integer id);
    DevUser selectByDevCode(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */
    List<DevUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */

    int updateByPrimaryKey(DevUser record);

    List<DevUser> selectByDevCodeAndPassword(String devCode, String password);
    List<HashMap<String,Object>> selectByParam2(@Param("params") Map<String,String> params);
    int updateByDid(int did,int statusAfter);
    int updateAllByDid(@Param("params")Map<String,String> params);
    List<HashMap<String,Object>> selectApplyInfoByParam(@Param("params")Map <String,String> params);
}